# permissions for end users to view dasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dask-viewer-role
rules:
- apiGroups:
  - compute.convect.ai
  resources:
  - dasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.convect.ai
  resources:
  - dasks/status
  verbs:
  - get
